# Generated by Django 3.1.3 on 2020-12-15 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20201215_2234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='set',
            name='clusters',
        ),
        migrations.AddField(
            model_name='cluster',
            name='sets',
            field=models.ManyToManyField(related_name='clusters', to='backend.Set'),
        ),
    ]
