# Generated by Django 3.1.3 on 2021-01-05 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20201215_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster',
            name='sets',
            field=models.ManyToManyField(blank=True, related_name='setClusters', to='backend.Set'),
        ),
    ]
