# Generated by Django 3.1.3 on 2021-01-05 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20210105_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster',
            name='sets',
            field=models.ManyToManyField(blank=True, related_name='clusters', to='backend.Set'),
        ),
    ]
