# Generated by Django 3.0.7 on 2021-08-23 21:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0007_auto_20210116_1041'),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeDescInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('block', models.CharField(blank=True, max_length=20, null=True)),
                ('subject', models.CharField(blank=True, max_length=20, null=True)),
                ('owner_username', models.CharField(max_length=30, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='practiceDescInput', to=settings.AUTH_USER_MODEL)),
                ('sets', models.ManyToManyField(blank=True, related_name='practiceDescInput', to='backend.Set')),
            ],
        ),
        migrations.CreateModel(
            name='PracticeDescSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('block', models.CharField(blank=True, max_length=20, null=True)),
                ('subject', models.CharField(blank=True, max_length=20, null=True)),
                ('owner_username', models.CharField(max_length=30, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='practiceDescSession', to=settings.AUTH_USER_MODEL)),
                ('practiceDescInputs', models.ManyToManyField(blank=True, related_name='practiceDescSession', to='backend.PracticeDescInput')),
                ('sets', models.ManyToManyField(blank=True, related_name='practiceDescSession', to='backend.Set')),
            ],
        ),
    ]
