# Generated by Django 3.0.7 on 2021-08-25 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_practicedescinput_practicedescsession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practicedescinput',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='practicedescsession',
            name='subject',
        ),
    ]
