# Generated by Django 3.0.7 on 2021-08-25 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20210825_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicedescinput',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
