# Generated by Django 3.0.6 on 2021-10-01 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_practicedescinput_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practicedescsession',
            name='practiceDescInputs',
            field=models.ManyToManyField(blank=True, related_name='practiceDescSessions', to='backend.PracticeDescInput'),
        ),
    ]
