# Generated by Django 3.0.6 on 2021-10-01 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_auto_20211001_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practicedescinput',
            name='block',
            field=models.CharField(blank=True, max_length=21, null=True),
        ),
    ]
