# Generated by Django 3.0.6 on 2021-10-02 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_auto_20211002_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practicedescsession',
            name='block',
            field=models.CharField(blank=True, max_length=22, null=True),
        ),
    ]
