# Generated by Django 3.0.6 on 2021-10-02 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_auto_20211002_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practicedescsession',
            name='block',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
