# Generated by Django 3.2 on 2022-01-28 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_alter_practiceidentifysession_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practiceidentifysession',
            name='questions',
            field=models.JSONField(blank=True, encoder=str, null=True),
        ),
        migrations.AlterField(
            model_name='practiceidentifysession',
            name='result',
            field=models.JSONField(blank=True, encoder=str, null=True),
        ),
    ]
