# Generated by Django 3.2 on 2022-01-28 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_auto_20220128_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practiceidentifysession',
            name='questions',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
