# Generated by Django 3.2 on 2022-01-29 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_alter_practiceidentifysession_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicedescsession',
            name='practiceType',
            field=models.CharField(blank=True, default='Description', max_length=40),
        ),
        migrations.AddField(
            model_name='practiceidentifysession',
            name='practiceType',
            field=models.CharField(blank=True, default='Identification', max_length=40),
        ),
    ]
