# Generated by Django 3.2 on 2022-01-29 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_auto_20220129_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practicedescsession',
            name='practiceType',
            field=models.CharField(default='Description', max_length=40),
        ),
        migrations.AlterField(
            model_name='practiceidentifysession',
            name='practiceType',
            field=models.CharField(default='Identification', max_length=40),
        ),
    ]
