# Generated by Django 3.2 on 2022-02-28 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_auto_20220129_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='references',
            field=models.TextField(blank=True, null=True),
        ),
    ]
