# Generated by Django 3.2 on 2022-02-28 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_set_references'),
    ]

    operations = [
        migrations.AddField(
            model_name='practiceidentifysession',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='practiceIdentifySession', to='backend.SetImage'),
        ),
    ]
