# Generated by Django 3.2 on 2022-09-21 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0025_session_setfeature'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='sport',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='set',
            name='highYield',
            field=models.TextField(blank=True, null=True),
        ),
    ]
