# Generated by Django 3.2.9 on 2021-12-08 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20211208_2320'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
