// Sets
export const GET_SETS = 'GET_SETS';
export const GET_IMAGES = 'GET_IMAGES';
export const GETBLOCK_SETS = 'GETBLOCK_SETS';
export const GET_SETS_BY_ID = 'GET_SETS_BY_ID';
export const GET_ALLSETS = 'GET_ALLSETS';
export const GET_MYSETS = 'GET_MYSETS';
export const DELETE_SET = 'DELETE_SET';
export const ADD_SET = 'ADD_SET';
export const UPDATE_SET = 'UPDATE_SET';
export const REPLACE_SET = 'REPLACE_SET';
export const SHOW_SET = 'SHOW_SET';
// Sets
export const GET_SESSIONS = 'GET_SESSIONS';
export const GETBLOCK_SESSIONS = 'GETBLOCK_SESSIONS';
export const GET_SESSIONS_BY_ID = 'GET_SESSIONS_BY_ID';
export const GET_ALLSESSIONS = 'GET_ALLSESSIONS';
export const GET_MYSESSIONS = 'GET_MYSESSIONS';
export const DELETE_SESSION = 'DELETE_SESSION';
export const ADD_SESSION = 'ADD_SESSION';
export const UPDATE_SESSION = 'UPDATE_SESSION';
export const REPLACE_SESSION = 'REPLACE_SESSION';
export const SHOW_SESSION = 'SHOW_SESSION';
//Clusters
export const GET_CLUSTERS = 'GET_CLUSTERS';
export const GETBLOCK_CLUSTERS = 'GETBLOCK_CLUSTERS';
export const GET_ALLCLUSTERS = 'GET_ALLCLUSTERS';
export const GET_MYCLUSTERS = 'GET_MYCLUSTERS';
export const DELETE_CLUSTER = 'DELETE_CLUSTER';
export const ADD_CLUSTER = 'ADD_CLUSTER';
export const UPDATE_CLUSTER = 'UPDATE_CLUSTER';
export const REPLACE_CLUSTER = 'REPLACE_CLUSTER';
export const SHOW_CLUSTER = 'SHOW_CLUSTER';

//Clusters
export const GET_EMAILLISTS = 'GET_EMAILLISTS';
export const GET_ALLEMAILLISTS = 'GET_ALLEMAILLISTS';
export const GET_MYEMAILLISTS = 'GET_MYEMAILLISTS';
export const DELETE_EMAILLIST = 'DELETE_EMAILLIST';
export const ADD_EMAILLIST = 'ADD_EMAILLIST';
export const UPDATE_EMAILLIST = 'UPDATE_EMAILLIST';
export const REPLACE_EMAILLIST = 'REPLACE_EMAILLIST';
export const SHOW_EMAILLIST = 'SHOW_EMAILLIST';

//PracticeDescSessions
export const GET_PRACTICEDESCSESSIONS = 'GET_PRACTICEDESCSESSIONS';
export const GET_ALLPRACTICEDESCSESSIONS = 'GET_ALLPRACTICEDESCSESSIONS';
export const GET_MYPRACTICEDESCSESSIONS = 'GET_MYPRACTICEDESCSESSIONS';
export const DELETE_PRACTICEDESCSESSION = 'DELETE_PRACTICEDESCSESSION';
export const ADD_PRACTICEDESCSESSION = 'ADD_PRACTICEDESCSESSION';
export const UPDATE_PRACTICEDESCSESSION = 'UPDATE_PRACTICEDESCSESSION';
export const REPLACE_PRACTICEDESCSESSION = 'REPLACE_PRACTICEDESCSESSION';
export const SHOW_PRACTICEDESCSESSION = 'SHOW_PRACTICEDESCSESSION';

//PracticeIdentifySessions
export const GET_PRACTICEIDENTIFYSESSIONS = 'GET_PRACTICEIDENTIFYSESSIONS';
export const GET_ALLPRACTICEIDENTIFYSESSIONS = 'GET_ALLPRACTICEIDENTIFYSESSIONS';
export const GET_MYPRACTICEIDENTIFYSESSIONS = 'GET_MYPRACTICEIDENTIFYSESSIONS';
export const DELETE_PRACTICEIDENTIFYSESSION = 'DELETE_PRACTICEIDENTIFYSESSION';
export const ADD_PRACTICEIDENTIFYSESSION = 'ADD_PRACTICEIDENTIFYSESSION';
export const UPDATE_PRACTICEIDENTIFYSESSION = 'UPDATE_PRACTICEIDENTIFYSESSION';
export const REPLACE_PRACTICEIDENTIFYSESSION = 'REPLACE_PRACTICEIDENTIFYSESSION';
export const SHOW_PRACTICEIDENTIFYSESSION = 'SHOW_PRACTICEIDENTIFYSESSION';


//PracticeDescInputs
export const GET_PRACTICEDESCINPUTS = 'GET_PRACTICEDESCINPUTS';
export const GET_ALLPRACTICEDESCINPUTS = 'GET_ALLPRACTICEDESCINPUTS';
export const GET_MYPRACTICEDESCINPUTS = 'GET_MYPRACTICEDESCINPUTS';
export const DELETE_PRACTICEDESCINPUT = 'DELETE_PRACTICEDESCINPUT';
export const ADD_PRACTICEDESCINPUT = 'ADD_PRACTICEDESCINPUT';
export const UPDATE_PRACTICEDESCINPUT = 'UPDATE_PRACTICEDESCINPUT';
export const REPLACE_PRACTICEDESCINPUT = 'REPLACE_PRACTICEDESCINPUT';
export const SHOW_PRACTICEDESCINPUT = 'SHOW_PRACTICEDESCINPUT';

export const GET_LEADS = 'GET_LEADS';
export const DELETE_LEAD = 'DELETE_LEAD';
export const ADD_LEAD = 'ADD_LEAD';
export const SHOW_LEAD = 'SHOW_LEAD';
export const GET_ERRORS = 'GET_ERRORS';
export const CREATE_MESSAGE = 'CREATE_MESSAGE';
export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const CLEAR_LEADS = 'CLEAR_LEADS';
//Loading
export const LOADING = 'LOADING';
export const LOADING_ON = 'LOADING_ON';
export const LOADING_OFF = 'LOADING_OFF';
